version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - surliciousdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwe123

  surlicious:
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo
    ports:
      - 8888:8080
    entrypoint: dub
    environment:
      VIRTUAL_HOST: surlicious.exomie.eu
      LETSENCRYPT_HOST: surlicious.exomie.eu
      LETSENCRYPT_EMAIL: exodiquas@gmail.com
    build:
      context: .
      dockerfile: ./Dockerfile

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8888:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: qwe123
  #     ME_CONFIG_MONGODB_URL: mongodb://root:qwe123@mongo:27017/

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  surliciousdata: