version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 8889:27017     
    volumes:
      - surliciousdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwe123
      MONGO_INITDB_DATABASE: Surlicious

  # surlicious:
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8080:8080
  #   entrypoint: dub
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwe123
      ME_CONFIG_MONGODB_URL: mongodb://root:qwe123@mongo:27017/
      
volumes:
  surliciousdata: